# Lesson content shared by build.py (audio) and the page (data).
# Word entries: "f|i|sh" marks letter teams (sh, ch, ck, ee, oo, ng) that are shown as one tile.
VOICES = [  # key, edge-tts voice, teacher name, accent, "f"/"m"
  ("ava", "en-US-AvaNeural", "Miss Ava", "American", "f"),
  ("emma", "en-US-EmmaNeural", "Miss Emma", "American", "f"),
  ("jenny", "en-US-JennyNeural", "Miss Jenny", "American", "f"),
  ("sonia", "en-GB-SoniaNeural", "Miss Sonia", "British", "f"),
  ("libby", "en-GB-LibbyNeural", "Miss Libby", "British", "f"),
  ("natasha", "en-AU-NatashaNeural", "Miss Natasha", "Australian", "f"),
  ("andrew", "en-US-AndrewNeural", "Mr Andrew", "American", "m"),
  ("brian", "en-US-BrianNeural", "Mr Brian", "American", "m"),
  ("ryan", "en-GB-RyanNeural", "Mr Ryan", "British", "m"),
  ("thomas", "en-GB-ThomasNeural", "Mr Thomas", "British", "m"),
  ("william", "en-AU-WilliamMultilingualNeural", "Mr William", "Australian", "m"),
]
VOWELS = {
  "a": {"word": "apple", "pic": "🍎", "src": "apple"},
  "e": {"word": "egg", "pic": "🥚", "src": "egg"},
  "i": {"word": "insect", "pic": "🐞", "src": "it"},
  "o": {"word": "octopus", "pic": "🐙", "src": "octopus"},
  "u": {"word": "umbrella", "pic": "☂️", "src": "up"},
}
FIRST_VOWEL = [("apple","🍎"),("ant","🐜"),("egg","🥚"),("elephant","🐘"),("insect","🐞"),
  ("iguana","🦎"),("octopus","🐙"),("otter","🦦"),("umbrella","☂️"),("up","⬆️")]
ALPHABET = [("b","ball","⚽"),("c","cat","🐱"),("d","dog","🐶"),("f","fish","🐟"),("g","goat","🐐"),("h","hat","🎩"),
  ("j","juice","🧃"),("k","kite","🪁"),("l","lion","🦁"),("m","moon","🌙"),("n","nest","🪺"),("p","pig","🐷"),
  ("r","rabbit","🐰"),("s","sun","☀️"),("t","tiger","🐯"),("v","van","🚐"),("w","web","🕸️"),("y","yoyo","🪀"),("z","zebra","🦓")]
SENTENCES = [("I see a cat.","🐱"),("The dog can run.","🐕"),("A fish can swim.","🐟"),("The sun is hot.","☀️"),
  ("The frog can hop.","🐸"),("The bus is red.","🚌"),("I like my hat.","🎩"),("Look at the moon.","🌙"),
  ("The duck is wet.","🦆"),("I can see a bee.","🐝")]

STAGES = [
  {"key":"vowels","name":"Vowel Valley","sub":"a e i o u","kind":"vowels","land":"valley","sticker":"🐴","animal":"horse",
   "games":["whichvowel","firstvowel","pop","whichvowel","firstvowel"]},
  {"key":"abc","name":"Alphabet Beach","sub":"Letter friends","kind":"alphabet","land":"beach","sticker":"🐬","animal":"dolphin","opts":3,"deck":6,
   "games":["letterfind","firstletter","letterfind","firstletter","letterfind"]},
  {"key":"two","name":"Two-Letter Town","sub":"up · go · hi","kind":"words","land":"town","sticker":"🐶","animal":"dog","opts":2,"deck":6,
   "words":[("up","🎈⬆️"),("go","🟢"),("no","🙅"),("hi","👋"),("me","🙋"),("we","👫"),("ox","🐂"),("in","🐱📦")],
   "games":["findpic","monster","build","memory","findpic"]},
  {"key":"a","name":"Cat Farm","sub":"cat · hat · van","kind":"words","land":"farm","sticker":"🐮","animal":"cow","opts":2,"deck":6,
   "words":[("cat","🐱"),("hat","🎩"),("bat","🦇"),("rat","🐀"),("van","🚐"),("fan","🪭"),("map","🗺️"),("bag","👜"),("jam","🍯"),("cap","🧢"),("pan","🍳"),("can","🥫")],
   "games":["findpic","monster","missing","build","memory"]},
  {"key":"ei","name":"Hen House","sub":"hen · pig · bed","kind":"words","land":"coop","sticker":"🐓","animal":"rooster","opts":3,"deck":6,
   "words":[("hen","🐔"),("bed","🛏️"),("pen","🖊️"),("web","🕸️"),("net","🥅"),("ten","🔟"),("leg","🦵"),("pig","🐷"),("pin","📌"),("six","6️⃣"),("zip","🤐"),("bin","🗑️"),("lip","👄"),("kid","🧒")],
   "games":["findpic","missing","monster","build","wordpop"]},
  {"key":"ou","name":"Sunny Pond","sub":"dog · sun · bus","kind":"words","land":"pond","sticker":"🦆","animal":"duck","opts":3,"deck":6,
   "words":[("dog","🐶"),("fox","🦊"),("box","📦"),("log","🪵"),("pot","🍲"),("hot","🥵"),("sun","☀️"),("bus","🚌"),("cup","🥤"),("bug","🐛"),("mug","☕"),("nut","🥜"),("hug","🤗"),("tub","🛁")],
   "games":["findpic","missing","memory","build","wordpop"]},
  {"key":"tricky","name":"Tricky Treehouse","sub":"the · I · you","kind":"tricky","land":"treehouse","sticker":"🐒","animal":"monkey","opts":3,"deck":6,
   "words":[("the",""),("and",""),("is",""),("i",""),("to",""),("you",""),("my",""),("see",""),("look",""),("like","")],
   "games":["monster","memory","wordpop","monster","monster"]},
  {"key":"blend","name":"Frog Forest","sub":"frog · star · drum","kind":"words","land":"forest","sticker":"🐸","animal":"frog","opts":3,"deck":6,
   "words":[("frog","🐸"),("crab","🦀"),("drum","🥁"),("star","⭐"),("flag","🚩"),("sled","🛷"),("swan","🦢"),("clap","👏"),("nest","🪺"),("milk","🥛"),("lamp","💡"),("tent","⛺"),("hand","✋"),("gift","🎁")],
   "games":["findpic","build","monster","missing","memory"]},
  {"key":"team","name":"Ship Shore","sub":"sh · ch · ee · oo","kind":"words","land":"ship","sticker":"🐳","animal":"whale","opts":3,"deck":6,
   "words":[("f|i|sh","🐟"),("sh|i|p","🚢"),("ch|i|p","🍟"),("d|u|ck","🦆"),("s|o|ck","🧦"),("r|o|ck","🪨"),("m|oo|n","🌙"),("b|oo|k","📖"),("t|r|ee","🌳"),("f|ee|t","🦶"),("k|i|ng","🤴"),("r|i|ng","💍")],
   "games":["findpic","build","monster","memory","findpic"]},
  {"key":"five","name":"Five-Letter Castle","sub":"horse · train","kind":"words","land":"castle","sticker":"🦁","animal":"lion","opts":3,"deck":6,
   "words":[("truck","🚚"),("snake","🐍"),("horse","🐴"),("sheep","🐑"),("train","🚂"),("house","🏠"),("mouse","🐭"),("plant","🪴"),("bread","🍞"),("chair","🪑"),("clock","⏰"),("crown","👑"),("heart","❤️"),("pizza","🍕"),("robot","🤖"),("tiger","🐯"),("zebra","🦓"),("whale","🐳"),("lemon","🍋")],
   "games":["findpic","missing","build","monster","memory"]},
  {"key":"sent","name":"Sentence Summit","sub":"Read whole sentences","kind":"sentences","land":"summit","sticker":"🦅","animal":"eagle","opts":3,"deck":5,
   "games":["sentpic","sentbuild","sentpic","sentbuild","sentpic"]},
]

PHRASES = {
  "welcome": "Hello, super reader! I'm your teacher, and this is Hoot the owl. Let's go on a reading adventure! Tap the first island to start.",
  "intro_vowels": "Welcome to Vowel Valley! These five letters are the vowels: A, E, I, O, U. Every word needs a vowel!",
  "intro_abc": "Welcome to Alphabet Beach! Every letter has a picture friend. B is for ball!",
  "intro_two": "Welcome to Two Letter Town! Let's put two letters together to make little words.",
  "intro_a": "Welcome to Cat Farm! All these words have the letter A in the middle, like cat and hat.",
  "intro_ei": "Welcome to Hen House! Here we read words with E and I in the middle, like hen and pig.",
  "intro_ou": "Welcome to Sunny Pond! Here we read words with O and U in the middle, like dog and sun.",
  "intro_tricky": "Welcome to Tricky Treehouse! Tricky words don't follow the rules, so we learn them by looking. Let's be word detectives!",
  "intro_blend": "Welcome to Frog Forest! In these words, two letters stand side by side at the start, like the F and R in frog.",
  "intro_team": "Welcome to Ship Shore! Some letters hold hands and make one new sound, like the S and H in ship.",
  "intro_five": "Welcome to Five Letter Castle! These are big words. I know you can do it!",
  "intro_sent": "Welcome to Sentence Summit! You climbed all the way to the top! Now you can read whole sentences. Wow!",
  "learn": "Tap the picture to hear the word. Tap a letter to hear its name.",
  "learnv": "Tap the big letter to hear its sound.",
  "learnabc": "Tap the big letter to meet its picture friend.",
  "learntricky": "Look carefully at each word. Tap it to hear it.",
  "learnsent": "Tap each word to hear it, or tap Read to me.",
  "ready": "Great learning! Now let's play a game!",
  "whichvowel": "Which vowel says",
  "firstvowel": "What sound does this word start with? Tap the vowel.",
  "firstletter": "Which letter does this word start with?",
  "findletter": "Can you find the letter",
  "pop": "Pop the vowel balloons! Find A, E, I, O, and U.",
  "findpic": "Read the word. Then tap the matching picture!",
  "build": "Build the word! Tap the letters in the right order.",
  "missing": "Uh oh! A letter fell off. Which letter is missing?",
  "monster": "I'm so hungry! Please feed me the word",
  "yum": "Yum yum! Thank you!",
  "yuck": "Hmm, that's not it. Try again!",
  "memory": "Find the matching pairs! Tap two cards to turn them over.",
  "match": "It's a match!",
  "wordpop": "Pop the word",
  "sentpic": "Read the sentence. Which picture shows it?",
  "sentbuild": "Put the words in order to make the sentence.",
  "readtome": "Let's read it together.",
  "praise1": "Great job!", "praise2": "Wow, you are a super reader!", "praise3": "Yes! That's right!",
  "praise4": "Amazing!", "praise5": "High five!", "praise6": "Brilliant reading!", "praise7": "You're a star!", "praise8": "Super duper!",
  "retry1": "Oops, try again!", "retry2": "Almost! Have another go!", "retry3": "Hmm, look again and try.",
  "star": "You did it! You earned a gold star!",
  "sticker": "And you got a new sticker for your sticker book!",
  "stickerbook": "Here is your sticker book. Tap a sticker to hear the real animal!",
  "alldone": "Hooray! You finished the whole reading adventure! You are a reading champion!",
  "locked": "That island is still locked. Finish the one before it first!",
  "popdone": "You popped all the vowels!",
  "helpread": "Let's read it together.",
  "dg_sh": "S and H hold hands. Together they say shh, like in ship.",
  "dg_ch": "C and H hold hands. Together they make the sound at the start of chip.",
  "dg_ck": "C and K hold hands. Together they make one sound, like at the end of duck.",
  "dg_ee": "Two E's hold hands. Together they make the sound at the end of tree.",
  "dg_oo": "Two O's hold hands. Together they make the sound in the middle of moon.",
  "dg_ng": "N and G hold hands. Together they make the sound at the end of king.",
}
PAIR_LEVELS = [  # Picture Pairs: card count, and which islands' words it draws from (easiest first)
  {"cards": 6, "from": ["a"]},
  {"cards": 8, "from": ["a", "ei"]},
  {"cards": 10, "from": ["ei", "ou"]},
  {"cards": 12, "from": ["a", "ei", "ou"]},
  {"cards": 16, "from": ["a", "ei", "ou", "blend"]},
  {"cards": 18, "from": ["ou", "blend"]},
  {"cards": 20, "from": ["blend", "team"]},
  {"cards": 22, "from": ["team", "five"]},
  {"cards": 24, "from": ["blend", "team", "five"]},
]
PHRASES.update({
  "stickerlocked": "Finish that island to win this sticker!",
  "pairs_pick": "Welcome to Picture Pairs! Every picture has a word friend. Pick a level to play.",
  "pairs_look": "Look carefully at all the cards. Read each word!",
  "pairs_go": "Now turn them over. Find each picture and its word!",
  "pairs_done": "Hooray! You found all the pairs!",
  "pairs_locked": "Finish the level before this one first!",
  "pairs_peek": "Here is a little peek to help you.",
})
for v in VOWELS: PHRASES[f"vsays_{v}"] = f"The letter {v.upper()} says"
WORD_TEXT = {"i": "I.", "a": "a.", "yoyo": "yo-yo."}  # how the voice should say these words
