# Lesson content shared by build.py (audio) and the page (data).
# Word entries: "f|i|sh" marks letter teams (sh, ch, ck, ee, oo, ng) that are shown as one tile.
VOICES = [  # key, edge-tts voice, teacher name, accent, "f"/"m"
  ("ava", "en-US-AvaNeural", "Miss Ava", "American", "f"),
  ("emma", "en-US-EmmaNeural", "Miss Emma", "American", "f"),
  ("jenny", "en-US-JennyNeural", "Miss Jenny", "American", "f"),
  ("sonia", "en-GB-SoniaNeural", "Miss Sonia", "British", "f"),
  ("libby", "en-GB-LibbyNeural", "Miss Libby", "British", "f"),
  ("natasha", "en-AU-NatashaNeural", "Miss Natasha", "Australian", "f"),
  ("andrew", "en-US-AndrewNeural", "Mr Andrew", "American", "m"),
  ("brian", "en-US-BrianNeural", "Mr Brian", "American", "m"),
  ("ryan", "en-GB-RyanNeural", "Mr Ryan", "British", "m"),
  ("thomas", "en-GB-ThomasNeural", "Mr Thomas", "British", "m"),
  ("william", "en-AU-WilliamMultilingualNeural", "Mr William", "Australian", "m"),
]
VOWELS = {
  "a": {"word": "apple", "pic": "🍎", "src": "apple"},
  "e": {"word": "egg", "pic": "🥚", "src": "egg"},
  "i": {"word": "insect", "pic": "🐞", "src": "it"},
  "o": {"word": "octopus", "pic": "🐙", "src": "octopus"},
  "u": {"word": "umbrella", "pic": "☂️", "src": "up"},
}
FIRST_VOWEL = [("apple","🍎"),("ant","🐜"),("egg","🥚"),("elephant","🐘"),("insect","🐞"),
  ("iguana","🦎"),("octopus","🐙"),("otter","🦦"),("umbrella","☂️"),("up","⬆️")]
ALPHABET = [("b","ball","⚽"),("c","cat","🐱"),("d","dog","🐶"),("f","fish","🐟"),("g","goat","🐐"),("h","hat","🎩"),
  ("j","juice","🧃"),("k","kite","🪁"),("l","lion","🦁"),("m","moon","🌙"),("n","nest","🪺"),("p","pig","🐷"),
  ("r","rabbit","🐰"),("s","sun","☀️"),("t","tiger","🐯"),("v","van","🚐"),("w","web","🕸️"),("y","yoyo","🪀"),("z","zebra","🦓")]
SENTENCES = [("I see a cat.","🐱"),("The dog can run.","🐕"),("A fish can swim.","🐟"),("The sun is hot.","☀️"),
  ("The frog can hop.","🐸"),("The bus is red.","🚌"),("I like my hat.","🎩"),("Look at the moon.","🌙"),
  ("The duck is wet.","🦆"),("I can see a bee.","🐝")]

STAGES = [
  {"key":"vowels","name":"Vowel Valley","sub":"a e i o u","kind":"vowels","land":"valley","sticker":"🐴","animal":"horse",
   "games":["whichvowel","firstvowel","pop","whichvowel","firstvowel"]},
  {"key":"abc","name":"Alphabet Beach","sub":"Letter friends","kind":"alphabet","land":"beach","sticker":"🐬","animal":"dolphin","opts":3,"deck":6,
   "games":["letterfind","firstletter","letterfind","firstletter","letterfind"]},
  {"key":"two","name":"Two-Letter Town","sub":"up · go · hi","kind":"words","land":"town","sticker":"🐶","animal":"dog","opts":2,"deck":6,
   "words":[("up","🎈⬆️"),("go","🟢"),("no","🙅"),("hi","👋"),("me","🙋"),("we","👫"),("ox","🐂"),("in","🐱📦")],
   "games":["findpic","monster","build","memory","findpic"]},
  {"key":"a","name":"Cat Farm","sub":"cat · hat · van","kind":"words","land":"farm","sticker":"🐮","animal":"cow","opts":2,"deck":6,
   "words":[("cat","🐱"),("hat","🎩"),("bat","🦇"),("rat","🐀"),("van","🚐"),("fan","🪭"),("map","🗺️"),("bag","👜"),("jam","🍯"),("cap","🧢"),("pan","🍳"),("can","🥫")],
   "games":["findpic","monster","missing","build","memory"]},
  {"key":"ei","name":"Hen House","sub":"hen · pig · bed","kind":"words","land":"coop","sticker":"🐓","animal":"rooster","opts":3,"deck":6,
   "words":[("hen","🐔"),("bed","🛏️"),("pen","🖊️"),("web","🕸️"),("net","🥅"),("ten","🔟"),("leg","🦵"),("pig","🐷"),("pin","📌"),("six","6️⃣"),("zip","🤐"),("bin","🗑️"),("lip","👄"),("kid","🧒")],
   "games":["findpic","missing","monster","build","wordpop"]},
  {"key":"ou","name":"Sunny Pond","sub":"dog · sun · bus","kind":"words","land":"pond","sticker":"🦆","animal":"duck","opts":3,"deck":6,
   "words":[("dog","🐶"),("fox","🦊"),("box","📦"),("log","🪵"),("pot","🍲"),("hot","🥵"),("sun","☀️"),("bus","🚌"),("cup","🥤"),("bug","🐛"),("mug","☕"),("nut","🥜"),("hug","🤗"),("tub","🛁")],
   "games":["findpic","missing","memory","build","wordpop"]},
  {"key":"tricky","name":"Tricky Treehouse","sub":"the · I · you","kind":"tricky","land":"treehouse","sticker":"🐒","animal":"monkey","opts":3,"deck":6,
   "words":[("the",""),("and",""),("is",""),("i",""),("to",""),("you",""),("my",""),("see",""),("look",""),("like","")],
   "games":["monster","memory","wordpop","monster","monster"]},
  {"key":"blend","name":"Frog Forest","sub":"frog · star · drum","kind":"words","land":"forest","sticker":"🐸","animal":"frog","opts":3,"deck":6,
   "words":[("frog","🐸"),("crab","🦀"),("drum","🥁"),("star","⭐"),("flag","🚩"),("sled","🛷"),("swan","🦢"),("clap","👏"),("nest","🪺"),("milk","🥛"),("lamp","💡"),("tent","⛺"),("hand","✋"),("gift","🎁")],
   "games":["findpic","build","monster","missing","memory"]},
  {"key":"team","name":"Ship Shore","sub":"sh · ch · ee · oo","kind":"words","land":"ship","sticker":"🐳","animal":"whale","opts":3,"deck":6,
   "words":[("f|i|sh","🐟"),("sh|i|p","🚢"),("ch|i|p","🍟"),("d|u|ck","🦆"),("s|o|ck","🧦"),("r|o|ck","🪨"),("m|oo|n","🌙"),("b|oo|k","📖"),("t|r|ee","🌳"),("f|ee|t","🦶"),("k|i|ng","🤴"),("r|i|ng","💍")],
   "games":["findpic","build","monster","memory","findpic"]},
  {"key":"five","name":"Five-Letter Castle","sub":"horse · train","kind":"words","land":"castle","sticker":"🦁","animal":"lion","opts":3,"deck":6,
   "words":[("truck","🚚"),("snake","🐍"),("horse","🐴"),("sheep","🐑"),("train","🚂"),("house","🏠"),("mouse","🐭"),("plant","🪴"),("bread","🍞"),("chair","🪑"),("clock","⏰"),("crown","👑"),("heart","❤️"),("pizza","🍕"),("robot","🤖"),("tiger","🐯"),("zebra","🦓"),("whale","🐳"),("lemon","🍋")],
   "games":["findpic","missing","build","monster","memory"]},
  {"key":"sent","name":"Sentence Summit","sub":"Read whole sentences","kind":"sentences","land":"summit","sticker":"🦅","animal":"eagle","opts":3,"deck":5,
   "games":["sentpic","sentbuild","sentpic","sentbuild","sentpic"]},
]

PHRASES = {
  "welcome": "Hello, super reader! I'm your teacher, and this is Hoot the owl. Let's go on a reading adventure! Tap the first island to start.",
  "intro_vowels": "Welcome to Vowel Valley! These five letters are the vowels: A, E, I, O, U. Every word needs a vowel!",
  "intro_abc": "Welcome to Alphabet Beach! Every letter has a picture friend. B is for ball!",
  "intro_two": "Welcome to Two Letter Town! Let's put two letters together to make little words.",
  "intro_a": "Welcome to Cat Farm! All these words have the letter A in the middle, like cat and hat.",
  "intro_ei": "Welcome to Hen House! Here we read words with E and I in the middle, like hen and pig.",
  "intro_ou": "Welcome to Sunny Pond! Here we read words with O and U in the middle, like dog and sun.",
  "intro_tricky": "Welcome to Tricky Treehouse! Tricky words don't follow the rules, so we learn them by looking. Let's be word detectives!",
  "intro_blend": "Welcome to Frog Forest! In these words, two letters stand side by side at the start, like the F and R in frog.",
  "intro_team": "Welcome to Ship Shore! Some letters hold hands and make one new sound, like the S and H in ship.",
  "intro_five": "Welcome to Five Letter Castle! These are big words. I know you can do it!",
  "intro_sent": "Welcome to Sentence Summit! You climbed all the way to the top! Now you can read whole sentences. Wow!",
  "learn": "Tap the picture to hear the word. Tap a letter to hear its name.",
  "learnv": "Tap the big letter to hear its sound.",
  "learnabc": "Tap the big letter to meet its picture friend.",
  "learntricky": "Look carefully at each word. Tap it to hear it.",
  "learnsent": "Tap each word to hear it, or tap Read to me.",
  "ready": "Great learning! Now let's play a game!",
  "whichvowel": "Which vowel says",
  "firstvowel": "What sound does this word start with? Tap the vowel.",
  "firstletter": "Which letter does this word start with?",
  "findletter": "Can you find the letter",
  "pop": "Pop the vowel balloons! Find A, E, I, O, and U.",
  "findpic": "Read the word. Then tap the matching picture!",
  "build": "Build the word! Tap the letters in the right order.",
  "missing": "Uh oh! A letter fell off. Which letter is missing?",
  "monster": "I'm so hungry! Please feed me the word",
  "yum": "Yum yum! Thank you!",
  "yuck": "Hmm, that's not it. Try again!",
  "memory": "Find the matching pairs! Tap two cards to turn them over.",
  "match": "It's a match!",
  "wordpop": "Pop the word",
  "sentpic": "Read the sentence. Which picture shows it?",
  "sentbuild": "Put the words in order to make the sentence.",
  "readtome": "Let's read it together.",
  "praise1": "Great job!", "praise2": "Wow, you are a super reader!", "praise3": "Yes! That's right!",
  "praise4": "Amazing!", "praise5": "High five!", "praise6": "Brilliant reading!", "praise7": "You're a star!", "praise8": "Super duper!",
  "retry1": "Oops, try again!", "retry2": "Almost! Have another go!", "retry3": "Hmm, look again and try.",
  "star": "You did it! You earned a gold star!",
  "sticker": "And you got a new sticker for your sticker book!",
  "stickerbook": "Here is your sticker book. Tap a sticker to hear the real animal!",
  "alldone": "Hooray! You finished the whole reading adventure! You are a reading champion!",
  "locked": "That island is still locked. Finish the one before it first!",
  "popdone": "You popped all the vowels!",
  "helpread": "Let's read it together.",
  "dg_sh": "S and H hold hands. Together they say shh, like in ship.",
  "dg_ch": "C and H hold hands. Together they make the sound at the start of chip.",
  "dg_ck": "C and K hold hands. Together they make one sound, like at the end of duck.",
  "dg_ee": "Two E's hold hands. Together they make the sound at the end of tree.",
  "dg_oo": "Two O's hold hands. Together they make the sound in the middle of moon.",
  "dg_ng": "N and G hold hands. Together they make the sound at the end of king.",
}
PAIR_LEVELS = [  # Picture Pairs: card count, and which islands' words it draws from (easiest first)
  {"cards": 6, "from": ["a"]},
  {"cards": 8, "from": ["a", "ei"]},
  {"cards": 10, "from": ["ei", "ou"]},
  {"cards": 12, "from": ["a", "ei", "ou"]},
  {"cards": 16, "from": ["a", "ei", "ou", "blend"]},
  {"cards": 18, "from": ["ou", "blend"]},
  {"cards": 20, "from": ["blend", "team"]},
  {"cards": 22, "from": ["team", "five"]},
  {"cards": 24, "from": ["blend", "team", "five"]},
]
PHRASES.update({
  "stickerlocked": "Finish that island to win this sticker!",
  "pairs_pick": "Welcome to Picture Pairs! Every picture has a word friend. Pick a level to play.",
  "pairs_look": "Look carefully at all the cards. Read each word!",
  "pairs_go": "Now turn them over. Find each picture and its word!",
  "pairs_done": "Hooray! You found all the pairs!",
  "pairs_locked": "Finish the level before this one first!",
  "pairs_peek": "Here is a little peek to help you.",
})
for v in VOWELS: PHRASES[f"vsays_{v}"] = f"The letter {v.upper()} says"
WORD_TEXT = {"i": "I.", "a": "a.", "yoyo": "yo-yo."}  # how the voice should say these words

# ---------- Talk Time: speaking practice (easiest first; picture where an emoji fits) ----------
TALK = {
 2: [("hi","👋"),("go","🟢"),("no","🙅"),("up","⬆️"),("me","🙋"),("we","👫"),("ox","🐂"),("in","📥"),("on","💡"),("ma","👩"),("pa","👨"),("oh","😮"),
     ("ow","🤕"),("ok","👌"),("ha","😂"),("ah","😌"),("my",""),("he","👦"),("be",""),("by",""),("do",""),("so",""),("to",""),("is",""),("it",""),
     ("if",""),("at",""),("am",""),("an",""),("as",""),("us","👨‍👩‍👦"),("of",""),("or","")],
 3: [("cat","🐱"),("hat","🎩"),("bat","🦇"),("rat","🐀"),("mat",""),("van","🚐"),("fan","🪭"),("can","🥫"),("pan","🍳"),("man","👨"),("ran","🏃"),("map","🗺️"),
     ("cap","🧢"),("tap","🚰"),("nap","😴"),("bag","👜"),("tag","🏷️"),("wag","🐕"),("jam","🍯"),("ham","🍖"),("dad","👨‍👧"),("sad","😢"),("mad","😠"),("lap",""),
     ("bed","🛏️"),("red","🔴"),("hen","🐔"),("pen","🖊️"),("ten","🔟"),("men",""),("net","🥅"),("pet","🐕"),("wet","💦"),("jet","✈️"),("vet","🩺"),("leg","🦵"),
     ("peg",""),("web","🕸️"),("yes","✅"),("get",""),("beg",""),("fed",""),
     ("pig","🐷"),("big",""),("dig","⛏️"),("wig",""),("fig",""),("pin","📌"),("bin","🗑️"),("win","🏆"),("fin","🦈"),("tin",""),("sit","🪑"),("hit",""),
     ("kit","🧰"),("lip","👄"),("hip",""),("zip","🤐"),("dip",""),("six","6️⃣"),("fix","🔧"),("mix","🥣"),("kid","🧒"),("lid",""),
     ("dog","🐶"),("log","🪵"),("fog","🌫️"),("hog","🐗"),("hot","🥵"),("pot","🍲"),("dot","⚫"),("cot",""),("not",""),("got",""),("box","📦"),("fox","🦊"),
     ("top",""),("mop","🧹"),("hop","🐇"),("pop","🍿"),("job","💼"),("pod","🫛"),
     ("sun","☀️"),("run","🏃"),("fun","🎉"),("bun","🥯"),("cup","🥤"),("pup","🐶"),("bus","🚌"),("bug","🐛"),("hug","🤗"),("mug","☕"),("rug",""),("jug","🏺"),
     ("nut","🥜"),("hut","🛖"),("cut","✂️"),("tub","🛁"),("mud",""),("gum","")],
 4: [("frog","🐸"),("crab","🦀"),("drum","🥁"),("star","⭐"),("flag","🚩"),("sled","🛷"),("swan","🦢"),("clap","👏"),("stop","🛑"),("spin","🌀"),("swim","🏊"),("skip",""),
     ("slip",""),("plum",""),("drip","💧"),("grin","😁"),("trip","🧳"),("trap","🪤"),("flip",""),("snap","🫰"),
     ("milk","🥛"),("lamp","💡"),("tent","⛺"),("hand","✋"),("gift","🎁"),("nest","🪺"),("belt",""),("desk",""),("jump","🤸"),("pond",""),("sand","🏖️"),("band",""),
     ("wind","🌬️"),("mask","🎭"),("help","🆘"),("bump",""),("fast","💨"),("list","📝"),("lost",""),("mint","🌿"),
     ("fish","🐟"),("ship","🚢"),("chip","🍟"),("shop","🛍️"),("shed",""),("duck","🦆"),("sock","🧦"),("rock","🪨"),("kick",""),("back",""),("lock","🔒"),("neck",""),
     ("bell","🔔"),("doll","🪆"),("ball","⚽"),("hill","⛰️"),("well",""),("king","🤴"),("ring","💍"),("wing","🪽"),("sing","🎤"),("song","🎵"),("bath","🛁"),("math","🧮"),
     ("moon","🌙"),("book","📖"),("food","🍔"),("foot","🦶"),("cook","🧑‍🍳"),("tree","🌳"),("feet","🦶"),("seed","🌱"),("keep",""),("deer","🦌"),
     ("boat","⛵"),("coat","🧥"),("goat","🐐"),("road","🛣️"),("soap","🧼"),("rain","🌧️"),("tail",""),("mail","📬"),("cake","🎂"),("lake","🏞️"),
     ("game","🎮"),("kite","🪁"),("bike","🚲"),("five","5️⃣"),("nine","9️⃣"),("bone","🦴"),("rose","🌹"),("home","🏠"),("cube","🧊"),("bear","🐻"),
     ("bird","🐦"),("fork","🍴"),("corn","🌽"),("card","🃏"),("farm","🚜"),("park",""),("girl","👧"),("baby","👶"),("lion","🦁"),("snow","❄️")],
 5: [("apple","🍎"),("horse","🐴"),("sheep","🐑"),("mouse","🐭"),("tiger","🐯"),("zebra","🦓"),("whale","🐳"),("snake","🐍"),("camel","🐫"),("koala","🐨"),
     ("panda","🐼"),("llama","🦙"),("puppy","🐶"),("bunny","🐰"),("chick","🐥"),("goose","🪿"),("eagle","🦅"),("shark","🦈"),("sloth","🦥"),("skunk","🦨"),
     ("otter","🦦"),("hippo","🦛"),("moose","🫎"),("train","🚂"),("truck","🚚"),("plane","✈️"),("ferry","⛴️"),("bread","🍞"),("pizza","🍕"),("lemon","🍋"),
     ("grape","🍇"),("peach","🍑"),("melon","🍈"),("candy","🍬"),("juice","🧃"),("water","💧"),("toast",""),("pasta","🍝"),("honey","🍯"),("bagel","🥯"),
     ("salad","🥗"),("fries","🍟"),("onion","🧅"),("beans","🫘"),("chair","🪑"),("table",""),("clock","⏰"),("house","🏠"),("plant","🪴"),("heart","❤️"),
     ("crown","👑"),("robot","🤖"),("ghost","👻"),("smile","😊"),("happy","😀"),("cloud","☁️"),("storm","⛈️"),("river","🏞️"),("beach","🏖️"),("ocean","🌊"),
     ("grass","🌱"),("stone","🪨"),("light","💡"),("phone","📱"),("radio","📻"),("piano","🎹"),("paint","🎨"),("brush","🖌️"),("books","📚"),("shirt","👕"),
     ("shoes","👟"),("dress","👗"),("socks","🧦"),("glove","🧤"),("scarf","🧣"),("watch","⌚"),("tooth","🦷"),("mouth","👄"),("hands","🙌"),("sleep","😴"),
     ("dance","💃"),("laugh","😂"),("music","🎵"),("party","🎉"),("queen","👸"),("fairy","🧚"),("magic","🪄"),("seven","7️⃣"),("three","3️⃣"),("eight","8️⃣"),
     ("green","🟢"),("black","⚫"),("white","⚪"),("brown","🟤"),("pink",""),("sweet","🍭"),("teddy","🧸"),("drink","🥤"),("jelly",""),("lunch","🍱")],
}
TALK[4] = [x for x in TALK[4] if x[0] not in {"keep", "back", "well", "lost"}]
TALK[5] = [x for x in TALK[5] if len(x[0]) == 5 and x[0] != "fries"] + [("spoon","🥄"),("snail","🐌")]
WORD_TEXT.update({"yoyo": "yo-yo.", "ok": "okay.", "ma": "ma.", "pa": "pa.", "us": "us.", "am": "am."})
PHRASES.update({
  "talk_pick": "Welcome to Talk Time! Here you practise saying words out loud, nice and clear. Listen to me first, then it's your turn!",
  "talk_listen": "Listen carefully.",
  "talk_turn": "Your turn! Tap the microphone and say",
  "talk_slow": "Now slowly.",
  "talk_great": "I heard you! You said it so clearly!",
  "talk_close": "So close! Let's say it one more time, nice and slow.",
  "talk_again": "Let's try again. Listen to me first.",
  "talk_start": "Listen to the start of the word.",
  "talk_middle": "Listen to the middle of the word.",
  "talk_end": "Listen to the end of the word.",
  "talk_moveon": "Good trying! Practice makes your words clearer. Let's go on.",
  "talk_loud": "I couldn't hear you. Say it a little louder, close to the phone!",
  "talk_nomic": "I can't hear the microphone yet. Ask a grown-up to allow the microphone.",
  "talk_check": "Did you sound the same as me? Tap the green thumb, or try again.",
  "talk_thisisyou": "This is you!",
  "talk_thisisme": "And this is me.",
  "talk_done": "You finished the lesson! Your talking is getting clearer and clearer!",
})

# ---------- Sound Garden: real letter sounds, blending, sounding out ----------
# letter: (source word the sound is cut from, how to cut it, key word, picture). Vowels use the cut short vowels.
LETTER_SOUNDS = {
  "s": ("sun", "fric", "sun", "☀️"), "a": (None, "vowel", "apple", "🍎"), "t": ("tub", "clip", "tiger", "🐯"), "p": ("pup", "clip", "pig", "🐷"),
  "i": (None, "vowel", "insect", "🐞"), "n": ("nut", "nasal", "nest", "🪺"), "m": ("mud", "nasal", "moon", "🌙"), "d": ("dug", "clip", "dog", "🐶"),
  "g": ("gut", "clip", "goat", "🐐"), "o": (None, "vowel", "octopus", "🐙"), "c": ("cup", "clip", "cat", "🐱"), "k": ("cub", "clip", "kite", "🪁"),
  "e": (None, "vowel", "egg", "🥚"), "u": (None, "vowel", "umbrella", "☂️"), "r": ("rug", "clip", "rabbit", "🐰"), "h": ("hut", "clip", "hat", "🎩"),
  "b": ("bug", "clip", "ball", "⚽"), "f": ("fun", "fric", "fish", "🐟"), "l": ("lug", "clip", "lion", "🦁"), "j": ("jug", "clip", "juice", "🧃"),
  "v": ("van", "vfric", "van", "🚐"), "w": ("one", "clip", "web", "🕸️"), "y": ("yum", "clip", "yoyo", "🪀"), "z": ("zip", "vfric", "zebra", "🦓"),
  "x": ("box", "tail", "box", "📦"), "qu": ("quick", "clip2", "queen", "👸"), "sh": ("shut", "fric", "ship", "🚢"), "ch": ("chug", "clip", "chip", "🍟"),
  "th": ("thumb", "fric", "thumb", "👍"),
}
# consonant+vowel blend: source word ending in a stop, cut before its closure
BLEND_SRC = {"sa": "sat", "ma": "mat", "ta": "tap", "pa": "pat", "na": "nap", "ca": "cat", "ba": "bat", "ha": "hat", "va": "vat", "ja": "jab",
  "me": "met", "te": "Ted", "pe": "pet", "ne": "net", "be": "bet", "le": "let", "he": "heck", "we": "wet",
  "si": "sit", "mi": "mitt", "ti": "tip", "pi": "pit", "ni": "nip", "di": "dip", "zi": "zip", "li": "lip", "ki": "kit", "bi": "bit",
  "so": "sock", "mo": "mop", "to": "top", "po": "pot", "no": "not", "do": "dot", "fo": "fog", "bo": "bog", "lo": "lot", "ho": "hot",
  "su": "sub", "mu": "mud", "tu": "tub", "pu": "pup", "nu": "nut", "bu": "bug", "cu": "cut"}
PHONICS = [  # steps shown in the Sound Garden, each with 5 lessons
  {"step": "Letter sounds", "lessons": [
     {"kind": "letters", "items": ["s", "a", "t", "p", "i", "n"]}, {"kind": "letters", "items": ["m", "d", "g", "o", "c", "k"]},
     {"kind": "letters", "items": ["e", "u", "r", "h", "b", "f"]}, {"kind": "letters", "items": ["l", "j", "v", "w", "y", "z"]},
     {"kind": "letters", "items": ["x", "qu", "sh", "ch", "th"]}]},
  {"step": "Blend two sounds", "lessons": [
     {"kind": "blends", "items": ["sa", "ma", "ta", "pa", "na", "ca"]}, {"kind": "blends", "items": ["me", "te", "pe", "ne", "be", "le"]},
     {"kind": "blends", "items": ["si", "mi", "ti", "pi", "ni", "di"]}, {"kind": "blends", "items": ["so", "mo", "to", "po", "no", "do"]},
     {"kind": "blends", "items": ["su", "mu", "tu", "pu", "nu", "bu"]}]},
  {"step": "Sound out words", "lessons": [
     {"kind": "phwords", "items": ["cat", "map", "bag", "hat", "van", "jam"]}, {"kind": "phwords", "items": ["hen", "bed", "pen", "web", "net", "leg"]},
     {"kind": "phwords", "items": ["pig", "six", "zip", "lip", "kid", "bin"]}, {"kind": "phwords", "items": ["dog", "fox", "box", "log", "pot", "hop"]},
     {"kind": "phwords", "items": ["sun", "bus", "cup", "bug", "mug", "nut"]}]},
  {"step": "Read by myself", "lessons": [{"kind": "phread", "items": []} for _ in range(5)]},
]
PHRASES.update({
  "ph_pick": "Welcome to Sound Garden! Every letter makes a sound. Learn the sounds, blend them together, and read real words!",
  "ph_board": "Tap any letter to hear its sound.",
  "ph_thisis": "This is", "ph_says": "says",
  "ph_intro_letters": "Let's learn letter sounds! Listen, then say each sound with me.",
  "ph_intro_blends": "Let's blend! Two sounds slide together and make a new sound.",
  "ph_intro_phwords": "Let's sound out words! Say each sound, then push them together to read the word.",
  "ph_intro_phread": "Now read all by yourself! If you need help, tap Sound it out.",
  "ph_soundfind": "Which letter makes this sound?",
  "ph_startsound": "What sound does this word start with?",
  "ph_soundpop": "Pop the letter that makes this sound!",
  "ph_blendfind": "Listen. Which blend did you hear?",
  "ph_blendbuild": "Build the blend you hear. Tap the two letters.",
  "ph_soundout": "Let's sound it out.",
  "ph_done": "Great work! You are reading with sounds!",
})

# ---------- Word Island 3D ----------
PHRASES.update({
  "wi_pick": "Welcome to Word Island! Walk, jump and read. Pick your adventure!",
  "wi_intro_easy": "Welcome to Letter Land! Push the stick to walk. Walk to the first sign, and jump over the logs!",
  "wi_intro_med": "Welcome to Word Builder! Walk into the letters to spell each word.",
  "wi_intro_hard": "Welcome to Sentence Trail! Walk into the word that finishes the sentence.",
  "wi_spell": "Let's spell",
  "wi_next": "Walk into the letter that says",
  "wi_missing": "Which word is missing? Walk into it!",
  "wi_thatis": "That is",
  "wi_done": "Hooray! You reached the trophy! You are a reading hero!",
})

# ---------- Sound World (open-world 3D letter sounds + speaking) ----------
PHRASES.update({
  "sw_intro": "Welcome to Sound World! Walk anywhere on the island and find the letter friends. Walk up to a letter to hear its sound, then say it with me!",
  "sw_turn_sound": "Your turn! Tap the microphone and say the sound",
  "sw_turn_word": "Now tap the microphone and say the word",
  "sw_heard": "I heard you! Great sound!",
  "sw_found": "You found a new letter friend!",
  "sw_find": "Let's find another letter. Follow the arrow!",
  "sw_all": "Wow! You found every letter sound! You are a sound superstar!",
  "sw_vowel": "This letter is a vowel. Vowels live in Vowel Village.",
})
